language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: CODECOV=1 DEFAULT=0

before_install:
  - sh -c "if [ '$CODECOV' = '1' ]; then sudo pip install codecov; fi"

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit --stderr; fi"
  - sh -c "if [ '$CODECOV' = '1' ]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi"

after_success:
  - sh -c "if [ '$CODECOV' = '1' ]; then codecov; fi"

notifications:
  email: false
